import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { AiwsError, writeText, fill, runShell } from '../util.js';
import { commandPrefixes } from '../stacks.js';
import { isHumanOnlyEntry } from '../gate.js';

const TOOL_MAP = {
  read: ['Read', 'Grep', 'Glob'],
  edit: ['Edit', 'MultiEdit'],
  write: ['Write'],
  bash: ['Bash'],
};

const LOCAL_CLI = 'aiws/adapters/cli';
// Workspace that carries its own CLI (the kit repo, or a project that vendors aiws/adapters): an exec path
// independent of PATH and npm link; Claude Code substitutes CLAUDE_PROJECT_DIR.
const LOCAL_GUARD = `node "\${CLAUDE_PROJECT_DIR}/${LOCAL_CLI}/bin/aiws.js" guard`;
// Project created with `aiws init`: the CLI is installed elsewhere and must be on PATH.
const PATH_GUARD = 'aiws guard';

function hasLocalCli(ws) {
  return fs.existsSync(path.join(ws.root, LOCAL_CLI, 'bin', 'aiws.js'));
}

/** The hook command `aiws sync claude` writes: runtime.yaml `claude.guard_command`, else by where the CLI lives. */
export function guardCommand(ws) {
  return ws.runtime.claude?.guard_command ?? (hasLocalCli(ws) ? LOCAL_GUARD : PATH_GUARD);
}

/**
 * Refuses to start agents when the guard hook of this workspace cannot work. A hook that crashes exits 1,
 * which Claude Code treats as non-blocking, so agents would silently run with diff-scope as their only check.
 */
export function preflight(ws) {
  const settingsFile = path.join(ws.root, '.claude', 'settings.json');
  if (!fs.existsSync(settingsFile)) {
    throw new AiwsError('The guard hook is not installed: .claude/settings.json is missing. Run `aiws sync claude` first.');
  }
  if (ws.runtime.claude?.guard_command) return; // custom command: the project owns it
  if (hasLocalCli(ws)) {
    const deps = path.join(ws.root, LOCAL_CLI, 'node_modules', 'yaml');
    if (!fs.existsSync(deps)) {
      throw new AiwsError(
        `The guard hook cannot start: dependencies are missing in ${LOCAL_CLI} of this workspace ` +
          `(every worktree needs its own). Run \`npm ci --omit=dev\` in ${path.join(ws.root, LOCAL_CLI)}.`
      );
    }
    return;
  }
  if (runShell('aiws --version', { cwd: ws.root }).status !== 0) {
    throw new AiwsError(
      'The guard hook cannot start: `aiws` is not on PATH. Run `npm link` in the aiws CLI folder, ' +
        'or set `claude.guard_command` in aiws/config/runtime.yaml.'
    );
  }
}

const GENERATED_NOTE = '<!-- GENERATED by `aiws sync claude` from aiws/. Do not edit; edit aiws/ and re-sync. -->';

function mapTools(tools) {
  return [...new Set((tools ?? ['read']).flatMap((t) => TOOL_MAP[t] ?? [t]))];
}

/**
 * Model of one run: `claude.phase_models.<phase>` wins, then `claude.agent_models.<agent id>`, then the
 * `model_hint` mapping in `claude.models`. A phase model lets an agent run on another model in one phase only,
 * for example `discovery` in `knowledge_update` but not in `aiws discover`. Without a phase (interactive
 * subagents written by `aiws sync claude`) only the agent counts.
 */
export function modelFor(ws, agent, phase = null) {
  const cfg = ws.runtime.claude ?? {};
  const own = (phase && cfg.phase_models?.[phase]) || cfg.agent_models?.[agent.id];
  if (own) return own;
  return agent.model_hint ? (cfg.models?.[agent.model_hint] ?? null) : null;
}

function yamlList(items) {
  return items.join(', ');
}

/** Generates CLAUDE.md, .claude/agents, .claude/skills and .claude/settings.json from aiws/. */
export function sync(ws) {
  const root = ws.root;
  const written = [];
  const claudeDir = path.join(root, '.claude');

  writeText(path.join(root, 'CLAUDE.md'), '@AGENTS.md\n');
  written.push('CLAUDE.md');

  const agentsDir = path.join(claudeDir, 'agents');
  fs.rmSync(agentsDir, { recursive: true, force: true });
  for (const id of ws.listAgents()) {
    const a = ws.agent(id);
    const model = modelFor(ws, a);
    const skills = a.skills ?? [];
    const fm = [
      '---',
      `name: ${id}`,
      `description: ${JSON.stringify(a.description ?? id)}`,
      `tools: ${yamlList(mapTools(a.tools))}`,
      ...(model ? [`model: ${model}`] : []),
      '---',
    ];
    const skillNote = skills.length
      ? `\n\n# Skills\nTrước khi làm, đọc các skill: ${skills.map((s) => `.claude/skills/${s}/SKILL.md`).join(', ')}.`
      : '';
    const scopeNote =
      '\n\n# Enforcement\nMọi thay đổi file bị kiểm tra bởi hook `aiws guard` và `aiws check diff-scope`. ' +
      'Ghi ngoài phạm vi của phase sẽ bị chặn hoặc bị revert.';
    writeText(path.join(agentsDir, `${id}.md`), `${fm.join('\n')}\n${GENERATED_NOTE}\n\n${a.body.trim()}${skillNote}${scopeNote}\n`);
    written.push(`.claude/agents/${id}.md`);
  }

  const skillsDir = path.join(claudeDir, 'skills');
  fs.rmSync(skillsDir, { recursive: true, force: true });
  for (const name of ws.listSkills()) {
    fs.cpSync(path.join(ws.aiwsDir, 'skills', name), path.join(skillsDir, name), { recursive: true });
    written.push(`.claude/skills/${name}/`);
  }

  writeText(path.join(claudeDir, 'settings.json'), JSON.stringify(settings(ws), null, 2) + '\n');
  written.push('.claude/settings.json');
  return written;
}

export function settings(ws) {
  const pol = ws.policies;
  const deny = [];
  for (const p of pol.read_deny ?? []) deny.push(`Read(${rel(p)})`);
  // Static deny rules cannot tell an AIWS phase from a maintainer editing aiws/ itself,
  // so only paths that nobody edits through Claude go here; the guard hook covers the rest.
  for (const p of hardProtected(pol)) deny.push(`Edit(${rel(p)})`);
  // Only the human-only gate commands (aiws approve, reject, ...) are denied statically; the rest of
  // bash_denylist (git commit/push, curl, aiws run...) is enforced by the guard hook inside a REQ
  // phase only, so a maintainer session can still commit and drive `aiws run` through Claude.
  for (const c of pol.bash_denylist ?? []) {
    if (isHumanOnlyEntry(c)) deny.push(`Bash(${c})`, `Bash(${c} *)`);
  }
  const guard = guardCommand(ws);
  return {
    permissions: { deny },
    hooks: {
      PreToolUse: [
        { matcher: 'Edit|Write|MultiEdit|NotebookEdit|Read', hooks: [{ type: 'command', command: guard }] },
        { matcher: 'Bash|PowerShell', hooks: [{ type: 'command', command: `${guard} --bash` }] },
      ],
    },
  };
}

export function hardProtected(pol) {
  const editable = new Set(pol.maintainer_editable ?? []);
  return (pol.protected_paths ?? []).filter((p) => !editable.has(p));
}

function rel(p) {
  return p.startsWith('./') || p.startsWith('/') ? p : `./${p}`;
}

/**
 * Tool whitelist for a headless run, e.g. ["Read","Grep","Glob","Write","Bash(dotnet test *)"].
 * `bash_allow` entries are policies.commands keys (`{side}` expands to every side) or literal prefixes;
 * the allowed prefixes are derived from the project's real build/test commands, whatever the language.
 */
export function allowedTools(ws, contract) {
  const tools = mapTools(contract.tools ?? ['read']).filter((t) => t !== 'Bash');
  const wantsBash = (contract.tools ?? []).includes('bash');
  if (wantsBash) {
    const pol = ws.policies;
    const sides = Object.keys(pol.sides ?? {});
    const prefixes = new Set();
    for (const entry of [...(contract.bash_allow ?? []), ...(pol.bash_allow_extra ?? [])]) {
      const keys = entry.includes('{side}') ? sides.map((s) => entry.replace('{side}', s)) : [entry];
      for (const key of keys) {
        const configured = pol.commands?.[key];
        // both OS variants: on Windows the orchestrator runs the `windows` form in cmd.exe,
        // but Claude Code's Bash tool is Git Bash, where the agent types the `posix` form
        const variants = typeof configured === 'string' ? [configured] : Object.values(configured ?? {});
        if (variants.length) variants.forEach((v) => commandPrefixes(v).forEach((p) => prefixes.add(p)));
        else if (!entry.includes('{side}') && !(key in (pol.commands ?? {}))) prefixes.add(key);
      }
    }
    // an agent that only knows the `windows` form retypes it for Git Bash with forward slashes (./mvnw.cmd)
    for (const p of [...prefixes]) if (p.includes('\\')) prefixes.add(p.replace(/\\/g, '/'));
    // nothing configured -> no shell at all (the orchestrator still builds and tests after the run)
    for (const p of prefixes) tools.push(`Bash(${p})`, `Bash(${p} *)`);
  }
  return tools;
}

/**
 * The form of a configured command that an agent types. Claude Code's Bash tool is a POSIX shell on every
 * OS (Git Bash on Windows), so the `posix` variant is the one that runs there.
 */
export function shellCommand(value) {
  if (value === undefined || value === null) return null;
  return typeof value === 'string' ? value : (value.posix ?? value.windows ?? null);
}

function quoteArg(a) {
  return `"${String(a).replace(/"/g, '\\"')}"`;
}

/** Runs `claude -p` headless. The prompt goes through stdin to avoid Windows command-line limits. */
export function runAgent(ws, { prompt, env, contract, agent }) {
  const cfg = ws.runtime.claude ?? {};
  const bin = cfg.command ?? 'claude';
  const args = ['-p', '--output-format', 'json', '--permission-mode', cfg.permission_mode ?? 'dontAsk'];
  const tools = allowedTools(ws, contract);
  args.push('--allowedTools', tools.join(','));
  const model = modelFor(ws, agent, env.AIWS_PHASE);
  if (model) args.push('--model', model);
  if (cfg.max_turns) args.push('--max-turns', String(cfg.max_turns));
  for (const extra of cfg.extra_args ?? []) args.push(fill(extra, {}));

  const cmdline = [bin, ...args.map(quoteArg)].join(' ');
  const started = Date.now();
  const res = spawnSync(cmdline, {
    cwd: ws.root,
    env,
    input: prompt,
    shell: true,
    encoding: 'utf8',
    maxBuffer: 256 * 1024 * 1024,
    windowsHide: true,
    timeout: (cfg.timeout_minutes ?? 30) * 60 * 1000,
  });
  const raw = res.stdout ?? '';
  const report = parse(raw);
  const ok = res.status === 0 && !report.is_error;
  const stderr = (res.stderr ?? '') + (res.error ? String(res.error) : '');
  return {
    ok,
    exitCode: res.status,
    stderr,
    usageLimit: ok ? null : (usageLimit(report.result) ?? usageLimit(stderr)),
    raw,
    report,
    command: cmdline,
    allowedTools: tools,
    durationMs: Date.now() - started,
  };
}

// What Claude Code answers when the usage window of the account is used up, for example
// "You've hit your session limit · resets 1:50pm (Asia/Bangkok)" or "Weekly limit reached ∙ resets Mon 10am".
const LIMIT_KIND = '(?:session|usage|weekly|daily|monthly|[\\w-]*hour|plan|model|opus|sonnet|rate)';
const USAGE_LIMIT = new RegExp(`\\b(?:hit|reached) your (?:${LIMIT_KIND} ){0,2}limit\\b|\\b${LIMIT_KIND} limit reached\\b`, 'i');

/**
 * The usage-limit message of a failed run, or null. Only the start of the text is tested: the message is
 * the whole answer of such a run, while an agent that merely writes about limits says so further down.
 */
export function usageLimit(text) {
  const head = String(text ?? '')
    .trim()
    .slice(0, 300);
  return USAGE_LIMIT.test(head) ? head.split(/\r?\n/)[0] : null;
}

/** Normalises `--output-format json` output into the evidence report shape. */
export function parse(raw) {
  try {
    const data = JSON.parse(raw.trim().split(/\r?\n/).filter(Boolean).at(-1) ?? '{}');
    return {
      is_error: Boolean(data.is_error),
      result: data.result ?? '',
      num_turns: data.num_turns ?? null,
      cost_usd: data.total_cost_usd ?? data.cost_usd ?? null,
      session_id: data.session_id ?? null,
      model: data.model ?? null,
    };
  } catch {
    return { is_error: true, result: raw.slice(0, 2000) };
  }
}
