import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { writeText, fill } from '../util.js';
import { commandPrefixes } from '../stacks.js';
import { isHumanOnlyEntry } from '../gate.js';

const TOOL_MAP = {
  read: ['Read', 'Grep', 'Glob'],
  edit: ['Edit', 'MultiEdit'],
  write: ['Write'],
  bash: ['Bash'],
};

// Exec path independent of PATH / npm link; Claude Code substitutes CLAUDE_PROJECT_DIR.
const DEFAULT_GUARD = 'node "${CLAUDE_PROJECT_DIR}/aiws/adapters/cli/bin/aiws.js" guard';

const GENERATED_NOTE = '<!-- GENERATED by `aiws sync claude` from aiws/. Do not edit; edit aiws/ and re-sync. -->';

function mapTools(tools) {
  return [...new Set((tools ?? ['read']).flatMap((t) => TOOL_MAP[t] ?? [t]))];
}

function modelFor(ws, hint) {
  const models = ws.runtime.claude?.models ?? {};
  return hint ? (models[hint] ?? null) : null;
}

function yamlList(items) {
  return items.join(', ');
}

/** Generates CLAUDE.md, .claude/agents, .claude/skills and .claude/settings.json from aiws/. */
export function sync(ws) {
  const root = ws.root;
  const written = [];
  const claudeDir = path.join(root, '.claude');

  writeText(path.join(root, 'CLAUDE.md'), '@AGENTS.md\n');
  written.push('CLAUDE.md');

  const agentsDir = path.join(claudeDir, 'agents');
  fs.rmSync(agentsDir, { recursive: true, force: true });
  for (const id of ws.listAgents()) {
    const a = ws.agent(id);
    const model = modelFor(ws, a.model_hint);
    const skills = a.skills ?? [];
    const fm = [
      '---',
      `name: ${id}`,
      `description: ${JSON.stringify(a.description ?? id)}`,
      `tools: ${yamlList(mapTools(a.tools))}`,
      ...(model ? [`model: ${model}`] : []),
      '---',
    ];
    const skillNote = skills.length
      ? `\n\n# Skills\nTrước khi làm, đọc các skill: ${skills.map((s) => `.claude/skills/${s}/SKILL.md`).join(', ')}.`
      : '';
    const scopeNote =
      '\n\n# Enforcement\nMọi thay đổi file bị kiểm tra bởi hook `aiws guard` và `aiws check diff-scope`. ' +
      'Ghi ngoài phạm vi của phase sẽ bị chặn hoặc bị revert.';
    writeText(path.join(agentsDir, `${id}.md`), `${fm.join('\n')}\n${GENERATED_NOTE}\n\n${a.body.trim()}${skillNote}${scopeNote}\n`);
    written.push(`.claude/agents/${id}.md`);
  }

  const skillsDir = path.join(claudeDir, 'skills');
  fs.rmSync(skillsDir, { recursive: true, force: true });
  for (const name of ws.listSkills()) {
    fs.cpSync(path.join(ws.aiwsDir, 'skills', name), path.join(skillsDir, name), { recursive: true });
    written.push(`.claude/skills/${name}/`);
  }

  writeText(path.join(claudeDir, 'settings.json'), JSON.stringify(settings(ws), null, 2) + '\n');
  written.push('.claude/settings.json');
  return written;
}

export function settings(ws) {
  const pol = ws.policies;
  const deny = [];
  for (const p of pol.read_deny ?? []) deny.push(`Read(${rel(p)})`);
  // Static deny rules cannot tell an AIWS phase from a maintainer editing aiws/ itself,
  // so only paths that nobody edits through Claude go here; the guard hook covers the rest.
  for (const p of hardProtected(pol)) deny.push(`Edit(${rel(p)})`);
  // Only the human-only gate commands (aiws approve, reject, ...) are denied statically; the rest of
  // bash_denylist (git commit/push, curl, aiws run...) is enforced by the guard hook inside a REQ
  // phase only, so a maintainer session can still commit and drive `aiws run` through Claude.
  for (const c of pol.bash_denylist ?? []) {
    if (isHumanOnlyEntry(c)) deny.push(`Bash(${c})`, `Bash(${c} *)`);
  }
  const guard = ws.runtime.claude?.guard_command ?? DEFAULT_GUARD;
  return {
    permissions: { deny },
    hooks: {
      PreToolUse: [
        { matcher: 'Edit|Write|MultiEdit|NotebookEdit|Read', hooks: [{ type: 'command', command: guard }] },
        { matcher: 'Bash|PowerShell', hooks: [{ type: 'command', command: `${guard} --bash` }] },
      ],
    },
  };
}

export function hardProtected(pol) {
  const editable = new Set(pol.maintainer_editable ?? []);
  return (pol.protected_paths ?? []).filter((p) => !editable.has(p));
}

function rel(p) {
  return p.startsWith('./') || p.startsWith('/') ? p : `./${p}`;
}

/**
 * Tool whitelist for a headless run, e.g. ["Read","Grep","Glob","Write","Bash(dotnet test *)"].
 * `bash_allow` entries are policies.commands keys (`{side}` expands to every side) or literal prefixes;
 * the allowed prefixes are derived from the project's real build/test commands, whatever the language.
 */
export function allowedTools(ws, contract) {
  const tools = mapTools(contract.tools ?? ['read']).filter((t) => t !== 'Bash');
  const wantsBash = (contract.tools ?? []).includes('bash');
  if (wantsBash) {
    const pol = ws.policies;
    const sides = Object.keys(pol.sides ?? {});
    const prefixes = new Set();
    for (const entry of [...(contract.bash_allow ?? []), ...(pol.bash_allow_extra ?? [])]) {
      const keys = entry.includes('{side}') ? sides.map((s) => entry.replace('{side}', s)) : [entry];
      for (const key of keys) {
        const configured = pol.commands?.[key];
        // both OS variants: on Windows the orchestrator runs the `windows` form in cmd.exe,
        // but Claude Code's Bash tool is Git Bash, where the agent types the `posix` form
        const variants = typeof configured === 'string' ? [configured] : Object.values(configured ?? {});
        if (variants.length) variants.forEach((v) => commandPrefixes(v).forEach((p) => prefixes.add(p)));
        else if (!entry.includes('{side}') && !(key in (pol.commands ?? {}))) prefixes.add(key);
      }
    }
    // nothing configured -> no shell at all (the orchestrator still builds and tests after the run)
    for (const p of prefixes) tools.push(`Bash(${p})`, `Bash(${p} *)`);
  }
  return tools;
}

function quoteArg(a) {
  return `"${String(a).replace(/"/g, '\\"')}"`;
}

/** Runs `claude -p` headless. The prompt goes through stdin to avoid Windows command-line limits. */
export function runAgent(ws, { prompt, env, contract, agent }) {
  const cfg = ws.runtime.claude ?? {};
  const bin = cfg.command ?? 'claude';
  const args = ['-p', '--output-format', 'json', '--permission-mode', cfg.permission_mode ?? 'dontAsk'];
  const tools = allowedTools(ws, contract);
  args.push('--allowedTools', tools.join(','));
  const model = modelFor(ws, agent.model_hint);
  if (model) args.push('--model', model);
  if (cfg.max_turns) args.push('--max-turns', String(cfg.max_turns));
  for (const extra of cfg.extra_args ?? []) args.push(fill(extra, {}));

  const cmdline = [bin, ...args.map(quoteArg)].join(' ');
  const started = Date.now();
  const res = spawnSync(cmdline, {
    cwd: ws.root,
    env,
    input: prompt,
    shell: true,
    encoding: 'utf8',
    maxBuffer: 256 * 1024 * 1024,
    windowsHide: true,
    timeout: (cfg.timeout_minutes ?? 30) * 60 * 1000,
  });
  const raw = res.stdout ?? '';
  const report = parse(raw);
  return {
    ok: res.status === 0 && !report.is_error,
    exitCode: res.status,
    stderr: (res.stderr ?? '') + (res.error ? String(res.error) : ''),
    raw,
    report,
    command: cmdline,
    allowedTools: tools,
    durationMs: Date.now() - started,
  };
}

/** Normalises `--output-format json` output into the evidence report shape. */
export function parse(raw) {
  try {
    const data = JSON.parse(raw.trim().split(/\r?\n/).filter(Boolean).at(-1) ?? '{}');
    return {
      is_error: Boolean(data.is_error),
      result: data.result ?? '',
      num_turns: data.num_turns ?? null,
      cost_usd: data.total_cost_usd ?? data.cost_usd ?? null,
      session_id: data.session_id ?? null,
      model: data.model ?? null,
    };
  } catch {
    return { is_error: true, result: raw.slice(0, 2000) };
  }
}
